### ISSUE TITLE
check list of dicts

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/dargs#10]
When something is a list of the dict with the same arguments, such as `model_devi_jobs`:

```json
"model_devi_jobs": [
  {"sys_idx": [0]},
  {"sys_idx": [1]}
]
```

Is it possible to check the value in the list?

**Comment by y1xiaoc** [comment]
Yes. The `repeat` parameter is for this purpose. Here's the [parameter](https://github.com/deepmodeling/dargs/blob/18f7a6d84eecb292af09d763eaa4f8d24fd158aa/dargs/dargs.py#L92) and the [example](https://github.com/deepmodeling/dargs/blob/18f7a6d84eecb292af09d763eaa4f8d24fd158aa/tests/test_checker.py#L94).

**Comment by njzjz** [comment]
Got it!
