### ISSUE TITLE
Failed to render document when default value is an empty string ""

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/dargs#18]
See https://docs.deepmodeling.com/projects/dpdispatcher/en/latest/resources.html#argument:resources/queue_name

![Screenshot from 2022-09-26 17-58-39](https://user-images.githubusercontent.com/9496702/192388226-7cc94a58-9ff4-4bb6-bcac-b5b17317c90c.png)

**Comment by y1xiaoc** [comment]
Should be fixed by [this line](https://github.com/deepmodeling/dargs/blob/65a51aa1cc4b9912b754c00db0e9bc3905b43617/dargs/dargs.py#L505). Please check and if it works I'll make a new release.

**Comment by njzjz** [comment]
LGTM
![image](https://user-images.githubusercontent.com/9496702/192405765-d7902292-1f4a-4215-8be1-c7f2320bae52.png)
