### ISSUE TITLE
The strange behavior of the default value for the optional dict Argument

### ISSUE THREAD

**Issue by wanghan-iapcm** [deepmodeling/dargs#28]
Please see the follow test:
```python
from dargs import Argument
def make_arguments():
    arg_foo = Argument("foo", int, optional=True, default=1)
    arg_bar = Argument("bar", dict, [arg_foo], optional=True, default={})
    return [arg_bar, arg_tar]

base = Argument("base", dict, make_arguments())
data = base.normalize_value({})
print(data)
data = base.normalize_value({'bar' : {}})
print(data)
```

The output of the code is 
```
{'bar': {'foo': 1}}
{'bar': {'foo': 1}}
```

In the first `normalize_value` command, I would expect the output to be 
```
{'bar': {}}
```
i.e. the default values of the dict items are not automatically set when I explicit write I want the default dict to be `{}`

**Comment by y1xiaoc** [comment]
shoud be fixed by the commit 10f4360

BTW @njzjz  it seems that the failed test is about formatting. Can it automatically fix the format for me? I'm sort of confused by the current CI now...

**Comment by njzjz** [comment]
@y1xiaoc Yes but only when you submit a PR...

**Comment by y1xiaoc** [comment]
Lol so bad. One more thing is that can we set black to be more compact on dicts? Currently the test dicts are sooo long that is hard to read

**Comment by njzjz** [comment]
> One more thing is that can we set black to be more compact on dicts?

No... Black intend to provide the least freedom to make all codes look the same...

**Comment by njzjz** [comment]
> it seems that the failed test is about formatting

11d3fc9ec197924534d9612a155dbfa9d3368583 fixed the style.

**Comment by njzjz** [comment]
@wanghan-iapcm When you find the problem has been resolved, you are free to close the issue and release a new version.

**Comment by wanghan-iapcm** [comment]
This issue has been fixed.
