### ISSUE TITLE
Allow any argument like `**kwarg`

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/dargs#5]
In dpdispatcher, `env` argument allows any sub-arguments. We may consider to add a new class like `AnyArgument` to handle this situation.

**Comment by y1xiaoc** [comment]
Sorry I didn't check this. Will an `Argument` with `dtype=dict` and no subfields do the work?

**Comment by njzjz** [comment]
I don't think it will work for argchecking... right?

**Comment by y1xiaoc** [comment]
Just added an [example](https://github.com/deepmodeling/dargs/blob/2882cd207831c2b9b4751e258493db109e5f3d66/tests/test_checker.py#L36) in test. Is this able to do the thing?

**Comment by njzjz** [comment]
> Just added an [example](https://github.com/deepmodeling/dargs/blob/2882cd207831c2b9b4751e258493db109e5f3d66/tests/test_checker.py#L36) in test. Is this able to do the thing?

No. I got the following error:
```
dargs.dargs.ArgumentKeyError: [at location `envs`] undefined key `aa` is not allowed in strict mode
```

**Comment by njzjz** [comment]
Although it works in the normal mode, it won't work in the strict mode.
